### PR TITLE
URW-93

### PR DESCRIPTION
**Pull request by aryan-damle**

### CODE REVIEW

**Review by sebastian-king — CHANGES_REQUESTED** [review]
Great first PR!
Only have a couple of tiny comments:
- Congratulations on being elected President! ;) ;) hehe, could you please update your title to just "Team Member"?
- Nice job on getting the filesize correct first time! Could you rename it from `.jpeg` to `.jpg`? That's probably one of the most pedantic things I've ever said, but it is important that we keep all of the file extensions exactly the same in case we ever want to batch process those images (for example, to change compression on all files at once).

I'd also love to chat sometime about what cars you work on, that sounds awesome!

**Review by sebastian-king — APPROVED** [review]

**Review by sebastian-king — APPROVED** [review]

**Review by Peyton232 — APPROVED** [review]
LGTM

**Review by Peyton232 — CHANGES_REQUESTED** [review]
Take out the anchor tags around your name <a>

**Comment by sebastian-king** [comment]
> Take out the anchor tags around your name

The anchor tags should stay, this is something I had Mason add (see #101)

**Review by Peyton232 — APPROVED** [review]

**Pull request merged**
