### PR TITLE
Nicole and Tyler Photo, and Tyler GitHub link fix

### PR DESCRIPTION
**Pull request by TylerAdamMartinez**

### CODE REVIEW

**Comment by ntindle** [comment]
Revert 606b026 and make it it’s own PR. Make sure to pull master first and rebase your branch to it

**Comment by ntindle** [comment]
There’s a heavy merge conflict in it is why

**Comment by ntindle** [comment]
Also why is 1990cfc deleting the whole file and re adding it

**Comment by TylerAdamMartinez** [comment]
@ntindle #33 because I used an extension in vscode call beautify and it properly indented that whole file, making appear that I deleted and readded everything.

**Comment by TylerAdamMartinez** [comment]
1990cfc

**Comment by TylerAdamMartinez** [comment]
It did the same thing, therefore, this will also appear to be a big commit

**Comment by ntindle** [comment]
Can you go though the whole repo and do it

**Comment by TylerAdamMartinez** [comment]
I don't believe I have write access if that's what you're asking.  So, I can't resolve the conflict.

**Comment by TylerAdamMartinez** [comment]
The conflict is occurring do to re beautifying

**Comment by ntindle** [comment]
LGTM

@sebastian-king?

**Comment by ntindle** [comment]
Also these should be on different branches

**Comment by sebastian-king** [comment]
I didn't want to deal with the merge conflict so I just push it up from my local version. PR is closed.

**Pull request closed without merging**
