### PR TITLE
Modified Contact_form/added timestamp

### PR DESCRIPTION
**Pull request by Wanhack**
closes URW-65
Requires SQL migrations

### CODE REVIEW

**Review by ntindle — DISMISSED** [review]

**Comment by sebastian-king** [comment]
Please remove the updated action

**Review by sebastian-king — CHANGES_REQUESTED** [review]
See other comment

**Comment by Peyton232** [comment]
> Please remove the updated action

What are you asking here?

**Comment by sebastian-king** [comment]
> > Please remove the updated action
> 
> What are you asking here?

The timestamp should not be updated when the database row is updated. I know my comment was a little cryptic but I talked to Wanhack about it in the discord voice on the weekend. Should be a quick change.

**Review by sebastian-king — APPROVED** [review]

**Pull request merged**
