### PR TITLE
URW-99

### PR DESCRIPTION
**Pull request by masonbesmer**
Added self to about us page (webmasters)

### CODE REVIEW

**Comment by Peyton232** [comment]
Looks good to me

**Comment by sebastian-king** [comment]
I have a fair few changes that I think the page needs. Please note @shotbyapony that most of these changes are not related to your addition of yourself to the page, but rather the general Web Team page which needs to be brought up to code because someone merged it before I had reviewed it previously.

- The page title should be "Our Web Team" or something similar, "Our Team" is already the title of the officers about us page
- The page needs to have a header image, and breadcrumbs. I think Peyton removed those accidentally when creating the page. If you want to create us a header image, you can do, if not, I will have one provided for you.
- The photos for the web team members should be a different directory, rather than `/images/bio-pics/`, perhaps let's use `/images/web-team-pics/`?
- The names are clickable but don't go anywhere. This should probably be an anchor tag to that specific person.

Alrighty, now specifically for your image, you will need to compress it. I recommend using FastStone Photo Resizer (it's free and pretty easy to use). Take a look at how large the files that are on the website currently are and aim for that. I don't think we actually use the "full" images so you don't need to provide that one.

Since you were so awesome and got your PR up there first, I think you can definitely do this! Of course, let me know what questions you have (anything at all) and always feel free to reach out in the discord and we can work on it together.

**Review by sebastian-king — DISMISSED** [review]
See other comment for requested changes.

**Comment by Peyton232** [comment]
Under your name you put webmaster | team member, change this to just team member

**Comment by shotbyapony** [comment]
Please review the changed files, I fixed the things you requested and placed a (temporary?) parallax image.

**Review by Peyton232 — DISMISSED** [review]
I may change that image later but it looks good for now. Looks like all the requested changes were made.

**Review by sebastian-king — CHANGES_REQUESTED** [review]
Will add details later!

**Comment by sebastian-king** [comment]
The file size police are back, sorry :)
The header image is 224 KB, can we compress that down to around 50 KB?
Your bio pic is also 66 KB which will need to be reduced, ideally to around 20 KB but it can be a bit larger if needed. Part of the reason your photo is larger is because it's a PNG file. It should be a JPG (.jpg, not .jpeg) file instead which generally has better compression, and it's also important to keep all of our images for a section with the same filetype. It helps if we ever want to run some batch processing on them, then we aren't dealing with multiple formats.

For the achor tags: what do you think about instead of removing them, making each web team member/officer have their own hash-code link? So for example, mine would be: http://untrobotics.com/about/our-team#sebastian-king. In order to make that hash-code link (anchor link) work, you simply need to set the id attribute on the `h6` element to `sebastian-king`, for example: `<h6 id="sebastian-king" ..... >` and then the browser will automatically be able to link to specific places on the page using those (ids. You could then re-add the `<a href...>` tags and make them link to that user's bio (that's generally just used so people can copy and paste that link to share a link straight to a specific bio, I know it's not much use linking to thing you're already looking at otherwise).

**Comment by sebastian-king** [comment]
One more tiny thing I want to add just to help you learn: I noticed you added a `p` tag into the `h6`. The `p` tag is short for a "paragraph tag", so those are designed for multi-line, inline text blocks. You added them into an `h6` tag, which is a "heading, size 6, tag", and of course you wouldn't usually have a paragraph in your headings :p. The reason I am mentioning this is because browsers add some default styling and behaviours to the common tags, like h6 and p, and when you combine things like a heading and a paragraph, sometimes you can get some unexpected conflicts with the default styling, and even inconsistent behaviour between browsers. I think if I needed a child element within a heading tag, I would usually just use `span` or `div` which are elements that have no default styling.

**Comment by shotbyapony** [comment]
Thank you, I will work on them over the weekend!

**Comment by AustinLeath** [comment]
@shotbyapony Let me know if you need any help on this. I might be able to allocate some time to this issue if need be.

**Review by Peyton232 — DISMISSED** [review]
LGTM

**Review by sebastian-king — CHANGES_REQUESTED** [review]
This is coming along really well! Thank you!
I have a couple more tiny changes for you:
- The header image should be in the /images/headers/ directory, and could you give it a more descriptive name, perhaps "web-team-page-header.jpg"?
- The anchor tags work great! The only issue left is that when you click on them, it takes you straight to the top of that user's section, which means the navbar is over part of the person's section. To fix this, we need to adjust where we put our id element. I think you need to create a new element after each user's div.bio-area, and make it "position: absolute" so it hovers above the element but doesn't take up any room. This will make the anchor tag fall in the perfect spot when it is clicked on to display the full section. :)
Let me know if you have any questions about that!

**Pull request merged**
