### PR TITLE
Changed banner on Login page

### PR DESCRIPTION
**Pull request by henlegay**

### CODE REVIEW

**Review by ntindle — CHANGES_REQUESTED** [review]
Remove the .idea files from the pr

**Comment by sebastian-king** [comment]
You need to remove your `.idea` files. These are specific to your IDE environment, if everyone checked out those files it would start reconfiguring everybody's JetBrains IDEs. These should be ignores in the .gitignore file, if they are not, please can you add it.

**Comment by sebastian-king** [comment]
You have changed the link to `activities.jpg` but I don't see that file included in the PR?

**Comment by ntindle** [comment]
> You have changed the link to `activities.jpg` but I don't see that file included in the PR?

This file already is up on the site. I verified it exist cause I thought the same.

**Comment by sebastian-king** [comment]
Apparently the `activities.jpg` file already exists. I don't think we should re-use the page banners. We have the ability to do something unique and creative for every page, and I think we should take advantage of that. Furthermore, one of the biggest UX benefits of having a unique banner for each page is that it makes it clearer what page you are on. You could get confused otherwise between two pages that have the same header. This can be especially confusing as you are sometimes unexpectedly redirected to the login page when you click on a protected link.

There's nothing particularly special about our current Mr Robot banner, I think I just googled "robot login" and found that. If you would like another image, I'll happily take submissions. Perhaps post it in the Discord first to get feedback from the whole team?

**Comment by sebastian-king** [comment]
PR superseded by #98. Closing.

**Pull request closed without merging**
